name: Deploy no GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Permissão para o conteúdo do repositório
  pages: write  # Permissão para escrever na branch gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Criar pasta public e copiar arquivos
        run: |
          mkdir public
          cp index.html public/
          cp style.css public/

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
